source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
platform :ios,'8.0'
target 'SkyUtilsPod_Example' do
  pod "SkyUtilsPod", :path => "../"
end

target 'SkyUtilsPod_Tests' do
  pod "SkyUtilsPod", :path => "../"

  
end
